// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: janction/audioStem/v1/query.proto

package audioStem

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryGetGameRequest is the request type for the Query/GetGame RPC
// method.
type QueryGetAudioStemTaskRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index,proto3" json:"index,omitempty"`
}

func (m *QueryGetAudioStemTaskRequest) Reset()         { *m = QueryGetAudioStemTaskRequest{} }
func (m *QueryGetAudioStemTaskRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAudioStemTaskRequest) ProtoMessage()    {}
func (*QueryGetAudioStemTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{0}
}
func (m *QueryGetAudioStemTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAudioStemTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAudioStemTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAudioStemTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAudioStemTaskRequest.Merge(m, src)
}
func (m *QueryGetAudioStemTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAudioStemTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAudioStemTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAudioStemTaskRequest proto.InternalMessageInfo

func (m *QueryGetAudioStemTaskRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

// QueryGetGameResponse is the response type for the Query/GetGame RPC
// method.
type QueryGetAudioStemTaskResponse struct {
	// Game defines the game at the requested index.
	AudioStemTask *AudioStemTask `protobuf:"bytes,1,opt,name=audio_stem_task,json=audioStemTask,proto3" json:"audio_stem_task,omitempty"`
}

func (m *QueryGetAudioStemTaskResponse) Reset()         { *m = QueryGetAudioStemTaskResponse{} }
func (m *QueryGetAudioStemTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAudioStemTaskResponse) ProtoMessage()    {}
func (*QueryGetAudioStemTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{1}
}
func (m *QueryGetAudioStemTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAudioStemTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAudioStemTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAudioStemTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAudioStemTaskResponse.Merge(m, src)
}
func (m *QueryGetAudioStemTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAudioStemTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAudioStemTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAudioStemTaskResponse proto.InternalMessageInfo

func (m *QueryGetAudioStemTaskResponse) GetAudioStemTask() *AudioStemTask {
	if m != nil {
		return m.AudioStemTask
	}
	return nil
}

// QueryGetGameRequest is the request type for the Query/GetGame RPC
// method.
type QueryGetAudioStemLogsRequest struct {
	ThreadId string `protobuf:"bytes,1,opt,name=threadId,proto3" json:"threadId,omitempty"`
}

func (m *QueryGetAudioStemLogsRequest) Reset()         { *m = QueryGetAudioStemLogsRequest{} }
func (m *QueryGetAudioStemLogsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAudioStemLogsRequest) ProtoMessage()    {}
func (*QueryGetAudioStemLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{2}
}
func (m *QueryGetAudioStemLogsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAudioStemLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAudioStemLogsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAudioStemLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAudioStemLogsRequest.Merge(m, src)
}
func (m *QueryGetAudioStemLogsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAudioStemLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAudioStemLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAudioStemLogsRequest proto.InternalMessageInfo

func (m *QueryGetAudioStemLogsRequest) GetThreadId() string {
	if m != nil {
		return m.ThreadId
	}
	return ""
}

// QueryGetGameResponse is the response type for the Query/GetGame RPC
// method.
type QueryGetAudioStemLogsResponse struct {
	// Game defines the game at the requested index.
	AudioStemLogs *AudioStemLogs `protobuf:"bytes,1,opt,name=audio_stem_logs,json=audioStemLogs,proto3" json:"audio_stem_logs,omitempty"`
}

func (m *QueryGetAudioStemLogsResponse) Reset()         { *m = QueryGetAudioStemLogsResponse{} }
func (m *QueryGetAudioStemLogsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAudioStemLogsResponse) ProtoMessage()    {}
func (*QueryGetAudioStemLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{3}
}
func (m *QueryGetAudioStemLogsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAudioStemLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAudioStemLogsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAudioStemLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAudioStemLogsResponse.Merge(m, src)
}
func (m *QueryGetAudioStemLogsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAudioStemLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAudioStemLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAudioStemLogsResponse proto.InternalMessageInfo

func (m *QueryGetAudioStemLogsResponse) GetAudioStemLogs() *AudioStemLogs {
	if m != nil {
		return m.AudioStemLogs
	}
	return nil
}

type QueryGetPendingAudioStemTaskRequest struct {
}

func (m *QueryGetPendingAudioStemTaskRequest) Reset()         { *m = QueryGetPendingAudioStemTaskRequest{} }
func (m *QueryGetPendingAudioStemTaskRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPendingAudioStemTaskRequest) ProtoMessage()    {}
func (*QueryGetPendingAudioStemTaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{4}
}
func (m *QueryGetPendingAudioStemTaskRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPendingAudioStemTaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPendingAudioStemTaskRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPendingAudioStemTaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPendingAudioStemTaskRequest.Merge(m, src)
}
func (m *QueryGetPendingAudioStemTaskRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPendingAudioStemTaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPendingAudioStemTaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPendingAudioStemTaskRequest proto.InternalMessageInfo

type QueryGetPendingAudioStemTaskResponse struct {
	AudioStemTasks []*AudioStemTask `protobuf:"bytes,1,rep,name=audio_stem_tasks,json=audioStemTasks,proto3" json:"audio_stem_tasks,omitempty"`
}

func (m *QueryGetPendingAudioStemTaskResponse) Reset()         { *m = QueryGetPendingAudioStemTaskResponse{} }
func (m *QueryGetPendingAudioStemTaskResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPendingAudioStemTaskResponse) ProtoMessage()    {}
func (*QueryGetPendingAudioStemTaskResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{5}
}
func (m *QueryGetPendingAudioStemTaskResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPendingAudioStemTaskResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPendingAudioStemTaskResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPendingAudioStemTaskResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPendingAudioStemTaskResponse.Merge(m, src)
}
func (m *QueryGetPendingAudioStemTaskResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPendingAudioStemTaskResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPendingAudioStemTaskResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPendingAudioStemTaskResponse proto.InternalMessageInfo

func (m *QueryGetPendingAudioStemTaskResponse) GetAudioStemTasks() []*AudioStemTask {
	if m != nil {
		return m.AudioStemTasks
	}
	return nil
}

type QueryGetWorkerRequest struct {
	Worker string `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
}

func (m *QueryGetWorkerRequest) Reset()         { *m = QueryGetWorkerRequest{} }
func (m *QueryGetWorkerRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetWorkerRequest) ProtoMessage()    {}
func (*QueryGetWorkerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{6}
}
func (m *QueryGetWorkerRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetWorkerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetWorkerRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetWorkerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetWorkerRequest.Merge(m, src)
}
func (m *QueryGetWorkerRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetWorkerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetWorkerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetWorkerRequest proto.InternalMessageInfo

func (m *QueryGetWorkerRequest) GetWorker() string {
	if m != nil {
		return m.Worker
	}
	return ""
}

type QueryGetWorkerResponse struct {
	Worker *Worker `protobuf:"bytes,1,opt,name=worker,proto3" json:"worker,omitempty"`
}

func (m *QueryGetWorkerResponse) Reset()         { *m = QueryGetWorkerResponse{} }
func (m *QueryGetWorkerResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetWorkerResponse) ProtoMessage()    {}
func (*QueryGetWorkerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9094a7effb89da29, []int{7}
}
func (m *QueryGetWorkerResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetWorkerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetWorkerResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetWorkerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetWorkerResponse.Merge(m, src)
}
func (m *QueryGetWorkerResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetWorkerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetWorkerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetWorkerResponse proto.InternalMessageInfo

func (m *QueryGetWorkerResponse) GetWorker() *Worker {
	if m != nil {
		return m.Worker
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetAudioStemTaskRequest)(nil), "janction.audioStem.v1.QueryGetAudioStemTaskRequest")
	proto.RegisterType((*QueryGetAudioStemTaskResponse)(nil), "janction.audioStem.v1.QueryGetAudioStemTaskResponse")
	proto.RegisterType((*QueryGetAudioStemLogsRequest)(nil), "janction.audioStem.v1.QueryGetAudioStemLogsRequest")
	proto.RegisterType((*QueryGetAudioStemLogsResponse)(nil), "janction.audioStem.v1.QueryGetAudioStemLogsResponse")
	proto.RegisterType((*QueryGetPendingAudioStemTaskRequest)(nil), "janction.audioStem.v1.QueryGetPendingAudioStemTaskRequest")
	proto.RegisterType((*QueryGetPendingAudioStemTaskResponse)(nil), "janction.audioStem.v1.QueryGetPendingAudioStemTaskResponse")
	proto.RegisterType((*QueryGetWorkerRequest)(nil), "janction.audioStem.v1.QueryGetWorkerRequest")
	proto.RegisterType((*QueryGetWorkerResponse)(nil), "janction.audioStem.v1.QueryGetWorkerResponse")
}

func init() { proto.RegisterFile("janction/audioStem/v1/query.proto", fileDescriptor_9094a7effb89da29) }

var fileDescriptor_9094a7effb89da29 = []byte{
	// 530 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xcf, 0x6b, 0x13, 0x41,
	0x14, 0xc7, 0x33, 0x4a, 0x8a, 0x9d, 0xa2, 0x96, 0xa1, 0x2d, 0x65, 0x6d, 0xd6, 0x66, 0x5a, 0x41,
	0xb4, 0xee, 0xd2, 0xb4, 0x22, 0xd4, 0x93, 0x5e, 0x44, 0x28, 0xfe, 0xa8, 0x82, 0xe0, 0xa5, 0x4c,
	0xb3, 0xc3, 0x76, 0x4d, 0x77, 0x5f, 0xba, 0x33, 0x89, 0x16, 0xc9, 0xc5, 0x93, 0x47, 0x41, 0xea,
	0x1f, 0x21, 0x08, 0xfe, 0x19, 0x1e, 0x0b, 0x5e, 0x3c, 0x4a, 0x22, 0xf8, 0x6f, 0xc8, 0xee, 0xce,
	0x24, 0xd9, 0x65, 0x37, 0x59, 0x7b, 0xdb, 0x37, 0x79, 0xdf, 0xf7, 0x3e, 0xef, 0xcd, 0x77, 0x82,
	0xeb, 0x6f, 0x58, 0xd0, 0x94, 0x1e, 0x04, 0x36, 0xeb, 0x38, 0x1e, 0xbc, 0x90, 0xdc, 0xb7, 0xbb,
	0x9b, 0xf6, 0x71, 0x87, 0x87, 0x27, 0x56, 0x3b, 0x04, 0x09, 0x64, 0x51, 0xa7, 0x58, 0xc3, 0x14,
	0xab, 0xbb, 0x69, 0x14, 0x28, 0xe5, 0x49, 0x9b, 0x8b, 0x44, 0x69, 0xac, 0xb8, 0x00, 0xee, 0x11,
	0xb7, 0x59, 0xdb, 0xb3, 0x59, 0x10, 0x80, 0x64, 0x51, 0xbe, 0xfe, 0xf5, 0x5a, 0x13, 0x84, 0x0f,
	0x22, 0xe9, 0x95, 0x69, 0x6a, 0x2c, 0xb8, 0xe0, 0x42, 0xfc, 0x69, 0x47, 0x5f, 0xc9, 0x29, 0xdd,
	0xc6, 0x2b, 0xcf, 0xa3, 0xa4, 0x47, 0x5c, 0x3e, 0xd0, 0x4d, 0x5f, 0x32, 0xd1, 0xda, 0xe3, 0xc7,
	0x1d, 0x2e, 0x24, 0x59, 0xc0, 0x55, 0x2f, 0x70, 0xf8, 0xbb, 0x65, 0xb4, 0x8a, 0x6e, 0xce, 0xee,
	0x25, 0x01, 0xf5, 0x71, 0xad, 0x40, 0x25, 0xda, 0x10, 0x08, 0x4e, 0x76, 0xf1, 0xd5, 0x78, 0x86,
	0x7d, 0x21, 0xb9, 0xbf, 0x2f, 0x99, 0x68, 0xc5, 0x05, 0xe6, 0x1a, 0xeb, 0x56, 0xee, 0xec, 0x56,
	0xba, 0xcc, 0x65, 0x36, 0x1e, 0xd2, 0x9d, 0x1c, 0xc8, 0x5d, 0x70, 0x85, 0x86, 0x34, 0xf0, 0x25,
	0x79, 0x18, 0x72, 0xe6, 0x3c, 0x76, 0x14, 0xe7, 0x30, 0xce, 0x45, 0x4d, 0xb4, 0xb9, 0xa8, 0x47,
	0xe0, 0x8a, 0xb2, 0xa8, 0x71, 0x99, 0x11, 0x6a, 0x14, 0xd2, 0x1b, 0x78, 0x4d, 0xb7, 0x7b, 0xc6,
	0x03, 0xc7, 0x0b, 0xdc, 0xbc, 0xb5, 0xd2, 0x2e, 0x5e, 0x9f, 0x9c, 0xa6, 0xe0, 0x9e, 0xe0, 0xf9,
	0xcc, 0x1e, 0x23, 0xba, 0x8b, 0xa5, 0x17, 0x79, 0x25, 0xb5, 0x48, 0x41, 0x6d, 0xbc, 0xa8, 0xfb,
	0xbe, 0x82, 0xb0, 0xc5, 0x43, 0xbd, 0xc2, 0x25, 0x3c, 0xf3, 0x36, 0x3e, 0x50, 0x0b, 0x54, 0x11,
	0x7d, 0x8a, 0x97, 0xb2, 0x02, 0x85, 0x76, 0x37, 0xa5, 0x98, 0x6b, 0xd4, 0x0a, 0x80, 0x94, 0x4c,
	0x25, 0x37, 0x4e, 0xab, 0xb8, 0x1a, 0x57, 0x24, 0x5f, 0x11, 0x9e, 0xcf, 0x1a, 0x88, 0x6c, 0x15,
	0x54, 0x99, 0x64, 0x52, 0x63, 0xfb, 0xff, 0x44, 0xc9, 0x00, 0xf4, 0xf6, 0xc7, 0xbf, 0xdf, 0x6f,
	0xa1, 0x0f, 0x3f, 0xff, 0x7c, 0xbe, 0xb0, 0x4a, 0x4c, 0x3b, 0xff, 0xf1, 0xbd, 0x8f, 0x0d, 0xdf,
	0x23, 0xdf, 0x32, 0xb0, 0xd1, 0x65, 0x97, 0x87, 0x1d, 0x33, 0x6b, 0x79, 0xd8, 0x71, 0x97, 0x52,
	0x6b, 0x04, 0xbb, 0x46, 0xea, 0x45, 0xb0, 0xda, 0xf5, 0x3d, 0xf2, 0x05, 0xe1, 0xd9, 0xe1, 0x9d,
	0x91, 0x8d, 0x29, 0x3d, 0x53, 0x5e, 0x30, 0xee, 0x94, 0xcc, 0x56, 0x68, 0x1b, 0x23, 0xb4, 0x3a,
	0xb9, 0x5e, 0x84, 0x96, 0x5c, 0x7f, 0x8f, 0x9c, 0x22, 0xbc, 0x5c, 0xe0, 0x7a, 0x41, 0x76, 0xa6,
	0x74, 0x9e, 0xf0, 0xa4, 0x8c, 0xfb, 0xe7, 0xd2, 0xaa, 0x19, 0x2a, 0x0f, 0xef, 0xfd, 0xe8, 0x9b,
	0xe8, 0xac, 0x6f, 0xa2, 0xdf, 0x7d, 0x13, 0x7d, 0x1a, 0x98, 0x95, 0xb3, 0x81, 0x59, 0xf9, 0x35,
	0x30, 0x2b, 0xaf, 0x6b, 0xae, 0x27, 0x0f, 0x3b, 0x07, 0x56, 0x13, 0xfc, 0x9c, 0xe1, 0x0e, 0x66,
	0xe2, 0x3f, 0xd2, 0xad, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xd8, 0xaa, 0x1c, 0xf8, 0x05,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// GetAudioStemTask returns the task based on the taskId
	GetAudioStemTask(ctx context.Context, in *QueryGetAudioStemTaskRequest, opts ...grpc.CallOption) (*QueryGetAudioStemTaskResponse, error)
	GetAudioStemLogs(ctx context.Context, in *QueryGetAudioStemLogsRequest, opts ...grpc.CallOption) (*QueryGetAudioStemLogsResponse, error)
	GetWorker(ctx context.Context, in *QueryGetWorkerRequest, opts ...grpc.CallOption) (*QueryGetWorkerResponse, error)
	GetPendingAudioStemTasks(ctx context.Context, in *QueryGetPendingAudioStemTaskRequest, opts ...grpc.CallOption) (*QueryGetPendingAudioStemTaskResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) GetAudioStemTask(ctx context.Context, in *QueryGetAudioStemTaskRequest, opts ...grpc.CallOption) (*QueryGetAudioStemTaskResponse, error) {
	out := new(QueryGetAudioStemTaskResponse)
	err := c.cc.Invoke(ctx, "/janction.audioStem.v1.Query/GetAudioStemTask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAudioStemLogs(ctx context.Context, in *QueryGetAudioStemLogsRequest, opts ...grpc.CallOption) (*QueryGetAudioStemLogsResponse, error) {
	out := new(QueryGetAudioStemLogsResponse)
	err := c.cc.Invoke(ctx, "/janction.audioStem.v1.Query/GetAudioStemLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetWorker(ctx context.Context, in *QueryGetWorkerRequest, opts ...grpc.CallOption) (*QueryGetWorkerResponse, error) {
	out := new(QueryGetWorkerResponse)
	err := c.cc.Invoke(ctx, "/janction.audioStem.v1.Query/GetWorker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetPendingAudioStemTasks(ctx context.Context, in *QueryGetPendingAudioStemTaskRequest, opts ...grpc.CallOption) (*QueryGetPendingAudioStemTaskResponse, error) {
	out := new(QueryGetPendingAudioStemTaskResponse)
	err := c.cc.Invoke(ctx, "/janction.audioStem.v1.Query/GetPendingAudioStemTasks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// GetAudioStemTask returns the task based on the taskId
	GetAudioStemTask(context.Context, *QueryGetAudioStemTaskRequest) (*QueryGetAudioStemTaskResponse, error)
	GetAudioStemLogs(context.Context, *QueryGetAudioStemLogsRequest) (*QueryGetAudioStemLogsResponse, error)
	GetWorker(context.Context, *QueryGetWorkerRequest) (*QueryGetWorkerResponse, error)
	GetPendingAudioStemTasks(context.Context, *QueryGetPendingAudioStemTaskRequest) (*QueryGetPendingAudioStemTaskResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) GetAudioStemTask(ctx context.Context, req *QueryGetAudioStemTaskRequest) (*QueryGetAudioStemTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioStemTask not implemented")
}
func (*UnimplementedQueryServer) GetAudioStemLogs(ctx context.Context, req *QueryGetAudioStemLogsRequest) (*QueryGetAudioStemLogsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAudioStemLogs not implemented")
}
func (*UnimplementedQueryServer) GetWorker(ctx context.Context, req *QueryGetWorkerRequest) (*QueryGetWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWorker not implemented")
}
func (*UnimplementedQueryServer) GetPendingAudioStemTasks(ctx context.Context, req *QueryGetPendingAudioStemTaskRequest) (*QueryGetPendingAudioStemTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPendingAudioStemTasks not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_GetAudioStemTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAudioStemTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAudioStemTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.audioStem.v1.Query/GetAudioStemTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAudioStemTask(ctx, req.(*QueryGetAudioStemTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAudioStemLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAudioStemLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAudioStemLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.audioStem.v1.Query/GetAudioStemLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAudioStemLogs(ctx, req.(*QueryGetAudioStemLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.audioStem.v1.Query/GetWorker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetWorker(ctx, req.(*QueryGetWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetPendingAudioStemTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPendingAudioStemTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetPendingAudioStemTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/janction.audioStem.v1.Query/GetPendingAudioStemTasks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetPendingAudioStemTasks(ctx, req.(*QueryGetPendingAudioStemTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "janction.audioStem.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAudioStemTask",
			Handler:    _Query_GetAudioStemTask_Handler,
		},
		{
			MethodName: "GetAudioStemLogs",
			Handler:    _Query_GetAudioStemLogs_Handler,
		},
		{
			MethodName: "GetWorker",
			Handler:    _Query_GetWorker_Handler,
		},
		{
			MethodName: "GetPendingAudioStemTasks",
			Handler:    _Query_GetPendingAudioStemTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "janction/audioStem/v1/query.proto",
}

func (m *QueryGetAudioStemTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAudioStemTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAudioStemTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAudioStemTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAudioStemTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAudioStemTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AudioStemTask != nil {
		{
			size, err := m.AudioStemTask.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAudioStemLogsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAudioStemLogsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAudioStemLogsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ThreadId) > 0 {
		i -= len(m.ThreadId)
		copy(dAtA[i:], m.ThreadId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ThreadId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAudioStemLogsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAudioStemLogsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAudioStemLogsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AudioStemLogs != nil {
		{
			size, err := m.AudioStemLogs.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPendingAudioStemTaskRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPendingAudioStemTaskRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPendingAudioStemTaskRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetPendingAudioStemTaskResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPendingAudioStemTaskResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPendingAudioStemTaskResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AudioStemTasks) > 0 {
		for iNdEx := len(m.AudioStemTasks) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.AudioStemTasks[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetWorkerRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetWorkerRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetWorkerRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Worker) > 0 {
		i -= len(m.Worker)
		copy(dAtA[i:], m.Worker)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Worker)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetWorkerResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetWorkerResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetWorkerResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Worker != nil {
		{
			size, err := m.Worker.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetAudioStemTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAudioStemTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AudioStemTask != nil {
		l = m.AudioStemTask.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAudioStemLogsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ThreadId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAudioStemLogsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AudioStemLogs != nil {
		l = m.AudioStemLogs.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPendingAudioStemTaskRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetPendingAudioStemTaskResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.AudioStemTasks) > 0 {
		for _, e := range m.AudioStemTasks {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetWorkerRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Worker)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetWorkerResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Worker != nil {
		l = m.Worker.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetAudioStemTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAudioStemTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAudioStemTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAudioStemTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAudioStemTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAudioStemTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AudioStemTask", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AudioStemTask == nil {
				m.AudioStemTask = &AudioStemTask{}
			}
			if err := m.AudioStemTask.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAudioStemLogsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAudioStemLogsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAudioStemLogsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ThreadId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ThreadId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAudioStemLogsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAudioStemLogsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAudioStemLogsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AudioStemLogs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AudioStemLogs == nil {
				m.AudioStemLogs = &AudioStemLogs{}
			}
			if err := m.AudioStemLogs.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPendingAudioStemTaskRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPendingAudioStemTaskRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPendingAudioStemTaskRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPendingAudioStemTaskResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPendingAudioStemTaskResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPendingAudioStemTaskResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AudioStemTasks", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AudioStemTasks = append(m.AudioStemTasks, &AudioStemTask{})
			if err := m.AudioStemTasks[len(m.AudioStemTasks)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetWorkerRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetWorkerRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetWorkerRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Worker = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetWorkerResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetWorkerResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetWorkerResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Worker", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Worker == nil {
				m.Worker = &Worker{}
			}
			if err := m.Worker.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
